# Site meta
title: Maskumal github page
description: This is github page of Maskumal
show_downloads: true
index_name: index.html
google_analytics:

# Site Author
author:
  name             : Maskumal
  avatar           : ""
  bio              : "My github page"
  location         : "Indonesia"
  email            : "maskumal43@gmail.com"
  uri              :
  home             :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "maskumal"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud	   :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          :

#file exclude to website
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
time-zone: Asia/Jakarta

